### ISSUE TITLE
TODO: Update Story

### ISSUE THREAD

**Issue by mathwhiz1212** [mathwhiz1212/A-Coalition-At-War#1]
# Storyline

- [ ]  Make the dialog flow smoother.
- [ ] Think through what the Coalition and Quarg are thinking after the wormhole opens. Write that down. Use that as material for dialog and future missions.

# Wormhole Systems
- [ ]  Create names for the wormhole systems.
- [ ]  Move them to locations that fit the story better.
             The Heliarch Wormhole needs to be moved East, the Quarg one might be fine, I'd need to check.
- [ ]  Add asteroids.

# Future Event Ideas

- [ ]  Event "jump drives looted" where the Coalition has looted enough Jump drives from the Quarg to equip them on their ships.

**Comment by lumbar527** [comment]
I find your Quarg lore a little odd. It's fine, because plugins don't need to follow existing lore!

> - [ ]  Think through what the Coalition and Quarg are thinking after the wormhole opens. Write that down. Use that as material for dialog and future missions.

I think the Quarg would have more interest in closing the wormhole (it exposes the Coalition to humanity) and finding out why it appeared.
The Coalition/Heliarch might be thinking that the Quarg want to invade them and retake their rule over them.

**Comment by mathwhiz1212** [comment]
@lumbar527 That's a good point. And the Quarg are probably thinking the Pug are messing with them. Maybe because they are...
